### ISSUE TITLE
Problema com o readthedocs apos atualizar as bibliotecas do mkdocs

### ISSUE THREAD

**Issue by azmovi** [dunossauro/notas-musicais#20]
Caso você tenha recebido esse erro após atualizar as bibliotecas do mkdocs-material e ter problemas no build da documentação com o readthedocs como esse:
```
Error: MkDocs encountered an error parsing the configuration fil cannot find module ...
```
Então para resolver esse problema eu editei o arquivo `.readthedocs.yaml` para que ele force a instalação de algumas bibliotecas usadas pelo mkdocs-material, ja que o readthedocs instala apenas o mkdocs, não entendi muito bem porque isso aconteceu, segue as instruções.
```yaml
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - python -m pip install --upgrade --no-cache-dir mkdocs-material
      - python -m pip install --upgrade --no-cache-dir mkdocs-macros-plugin
      - python -m pip install --upgrade --no-cache-dir mkdocstrings-python
```

Dessa forma forçamos o readthedocs baixar nossas dependências, não entendi porque isso aconteceu e porque isso funcionou.
